task:
  name: Build NixOS Kernel (master)
  timeout_in: 180m
  container:
    image: nixos/nix:latest
    cpu: 8
    memory: 16G
  env:
    CACHIX_AUTH_TOKEN: ENCRYPTED[!cc7126ff7084e71fb6117f512316fb55f0845fd36d3ba5ffdddc879904c7578be77a3ade4043337a0aa27898ec23db26!]
    GITHUB_TOKEN: ENCRYPTED[!53f76a904f9a61d9f6a23861f6dfb56d7bd1bc8f14d0c1aa433a3452972fb415f92e4bc5237d903f65442e03142d546f!]
  setup_nix_script: |
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  build_script: |
    git clone https://oauth2:$GITHUB_TOKEN@github.com/kalishxern/nixos-config
    nix run nixpkgs#cachix -- authtoken $CACHIX_AUTH_TOKEN
    nix run nixpkgs#cachix -- use nixos-kernel-master
    nix run nixpkgs#cachix -- watch-exec nixos-kernel-master -- \
      nix build ./nixos-config#nixosConfigurations.nixos-ci.config.boot.kernelPackages.kernel \
      --no-link --print-out-paths
